server:
  port: 9000

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://blob-dev-mysql-1/blob
    username: blob
    password: blob
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: false
      settings:
        web-allow-others: false