name: Develop Deploy to AWS EC2

on:
  push:
    branches:
      - develop
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.6.0
        with:
          arguments: build

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: Blob Server
          path: build/libs/blob-application.jar
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v2
      with:
        name: Blob Server
        path: build/libs/
      
    - name: Deploy to EC2
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
        chmod 400 private_key.pem
        scp -i ./private_key.pem -o StrictHostKeyChecking=no build/libs/blob-application.jar ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:./workspace/dev
        ssh -i ./private_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} '
          cd workspace/dev
          sh develop.sh
        '
        rm -f private_key.pem
